import type { Knex } from "knex";

const COUNTRIES = [
  // ── Africa (54 countries – all sovereign states) ──
  { name: "Algeria", capital: "Algiers", flag_url: "🇩🇿", continent: "Africa", region: "North Africa" },
  { name: "Angola", capital: "Luanda", flag_url: "🇦🇴", continent: "Africa", region: "Southern Africa" },
  { name: "Benin", capital: "Porto-Novo", flag_url: "🇧🇯", continent: "Africa", region: "West Africa" },
  { name: "Botswana", capital: "Gaborone", flag_url: "🇧🇼", continent: "Africa", region: "Southern Africa" },
  { name: "Burkina Faso", capital: "Ouagadougou", flag_url: "🇧🇫", continent: "Africa", region: "West Africa" },
  { name: "Burundi", capital: "Gitega", flag_url: "🇧🇮", continent: "Africa", region: "East Africa" },
  { name: "Cabo Verde", capital: "Praia", flag_url: "🇨🇻", continent: "Africa", region: "West Africa" },
  { name: "Cameroon", capital: "Yaoundé", flag_url: "🇨🇲", continent: "Africa", region: "Central Africa" },
  { name: "Central African Republic", capital: "Bangui", flag_url: "🇨🇫", continent: "Africa", region: "Central Africa" },
  { name: "Chad", capital: "N'Djamena", flag_url: "🇹🇩", continent: "Africa", region: "Central Africa" },
  { name: "Comoros", capital: "Moroni", flag_url: "🇰🇲", continent: "Africa", region: "East Africa" },
  { name: "Democratic Republic of the Congo", capital: "Kinshasa", flag_url: "🇨🇩", continent: "Africa", region: "Central Africa" },
  { name: "Republic of the Congo", capital: "Brazzaville", flag_url: "🇨🇬", continent: "Africa", region: "Central Africa" },
  { name: "Djibouti", capital: "Djibouti", flag_url: "🇩🇯", continent: "Africa", region: "East Africa" },
  { name: "Egypt", capital: "Cairo", flag_url: "🇪🇬", continent: "Africa", region: "North Africa" },
  { name: "Equatorial Guinea", capital: "Malabo", flag_url: "🇬🇶", continent: "Africa", region: "Central Africa" },
  { name: "Eritrea", capital: "Asmara", flag_url: "🇪🇷", continent: "Africa", region: "East Africa" },
  { name: "Eswatini", capital: "Mbabane", flag_url: "🇸🇿", continent: "Africa", region: "Southern Africa" },
  { name: "Ethiopia", capital: "Addis Ababa", flag_url: "🇪🇹", continent: "Africa", region: "East Africa" },
  { name: "Gabon", capital: "Libreville", flag_url: "🇬🇦", continent: "Africa", region: "Central Africa" },
  { name: "Gambia", capital: "Banjul", flag_url: "🇬🇲", continent: "Africa", region: "West Africa" },
  { name: "Ghana", capital: "Accra", flag_url: "🇬🇭", continent: "Africa", region: "West Africa" },
  { name: "Guinea", capital: "Conakry", flag_url: "🇬🇳", continent: "Africa", region: "West Africa" },
  { name: "Guinea-Bissau", capital: "Bissau", flag_url: "🇬🇼", continent: "Africa", region: "West Africa" },
  { name: "Ivory Coast", capital: "Yamoussoukro", flag_url: "🇨🇮", continent: "Africa", region: "West Africa" },
  { name: "Kenya", capital: "Nairobi", flag_url: "🇰🇪", continent: "Africa", region: "East Africa" },
  { name: "Lesotho", capital: "Maseru", flag_url: "🇱🇸", continent: "Africa", region: "Southern Africa" },
  { name: "Liberia", capital: "Monrovia", flag_url: "🇱🇷", continent: "Africa", region: "West Africa" },
  { name: "Libya", capital: "Tripoli", flag_url: "🇱🇾", continent: "Africa", region: "North Africa" },
  { name: "Madagascar", capital: "Antananarivo", flag_url: "🇲🇬", continent: "Africa", region: "East Africa" },
  { name: "Malawi", capital: "Lilongwe", flag_url: "🇲🇼", continent: "Africa", region: "Southern Africa" },
  { name: "Mali", capital: "Bamako", flag_url: "🇲🇱", continent: "Africa", region: "West Africa" },
  { name: "Mauritania", capital: "Nouakchott", flag_url: "🇲🇷", continent: "Africa", region: "West Africa" },
  { name: "Mauritius", capital: "Port Louis", flag_url: "🇲🇺", continent: "Africa", region: "East Africa" },
  { name: "Morocco", capital: "Rabat", flag_url: "🇲🇦", continent: "Africa", region: "North Africa" },
  { name: "Mozambique", capital: "Maputo", flag_url: "🇲🇿", continent: "Africa", region: "Southern Africa" },
  { name: "Namibia", capital: "Windhoek", flag_url: "🇳🇦", continent: "Africa", region: "Southern Africa" },
  { name: "Niger", capital: "Niamey", flag_url: "🇳🇪", continent: "Africa", region: "West Africa" },
  { name: "Nigeria", capital: "Abuja", flag_url: "🇳🇬", continent: "Africa", region: "West Africa" },
  { name: "Rwanda", capital: "Kigali", flag_url: "🇷🇼", continent: "Africa", region: "East Africa" },
  { name: "São Tomé and Príncipe", capital: "São Tomé", flag_url: "🇸🇹", continent: "Africa", region: "Central Africa" },
  { name: "Senegal", capital: "Dakar", flag_url: "🇸🇳", continent: "Africa", region: "West Africa" },
  { name: "Seychelles", capital: "Victoria", flag_url: "🇸🇨", continent: "Africa", region: "East Africa" },
  { name: "Sierra Leone", capital: "Freetown", flag_url: "🇸🇱", continent: "Africa", region: "West Africa" },
  { name: "Somalia", capital: "Mogadishu", flag_url: "🇸🇴", continent: "Africa", region: "East Africa" },
  { name: "South Africa", capital: "Pretoria", flag_url: "🇿🇦", continent: "Africa", region: "Southern Africa" },
  { name: "South Sudan", capital: "Juba", flag_url: "🇸🇸", continent: "Africa", region: "East Africa" },
  { name: "Sudan", capital: "Khartoum", flag_url: "🇸🇩", continent: "Africa", region: "North Africa" },
  { name: "Tanzania", capital: "Dodoma", flag_url: "🇹🇿", continent: "Africa", region: "East Africa" },
  { name: "Togo", capital: "Lomé", flag_url: "🇹🇬", continent: "Africa", region: "West Africa" },
  { name: "Tunisia", capital: "Tunis", flag_url: "🇹🇳", continent: "Africa", region: "North Africa" },
  { name: "Uganda", capital: "Kampala", flag_url: "🇺🇬", continent: "Africa", region: "East Africa" },
  { name: "Zambia", capital: "Lusaka", flag_url: "🇿🇲", continent: "Africa", region: "Southern Africa" },
  { name: "Zimbabwe", capital: "Harare", flag_url: "🇿🇼", continent: "Africa", region: "Southern Africa" },

  // ── Europe (44 countries) ──
  { name: "Albania", capital: "Tirana", flag_url: "🇦🇱", continent: "Europe", region: "Southern Europe" },
  { name: "Andorra", capital: "Andorra la Vella", flag_url: "🇦🇩", continent: "Europe", region: "Southern Europe" },
  { name: "Austria", capital: "Vienna", flag_url: "🇦🇹", continent: "Europe", region: "Western Europe" },
  { name: "Belarus", capital: "Minsk", flag_url: "🇧🇾", continent: "Europe", region: "Eastern Europe" },
  { name: "Belgium", capital: "Brussels", flag_url: "🇧🇪", continent: "Europe", region: "Western Europe" },
  { name: "Bosnia and Herzegovina", capital: "Sarajevo", flag_url: "🇧🇦", continent: "Europe", region: "Southern Europe" },
  { name: "Bulgaria", capital: "Sofia", flag_url: "🇧🇬", continent: "Europe", region: "Eastern Europe" },
  { name: "Croatia", capital: "Zagreb", flag_url: "🇭🇷", continent: "Europe", region: "Southern Europe" },
  { name: "Cyprus", capital: "Nicosia", flag_url: "🇨🇾", continent: "Europe", region: "Southern Europe" },
  { name: "Czech Republic", capital: "Prague", flag_url: "🇨🇿", continent: "Europe", region: "Eastern Europe" },
  { name: "Denmark", capital: "Copenhagen", flag_url: "🇩🇰", continent: "Europe", region: "Northern Europe" },
  { name: "Estonia", capital: "Tallinn", flag_url: "🇪🇪", continent: "Europe", region: "Northern Europe" },
  { name: "Finland", capital: "Helsinki", flag_url: "🇫🇮", continent: "Europe", region: "Northern Europe" },
  { name: "France", capital: "Paris", flag_url: "🇫🇷", continent: "Europe", region: "Western Europe" },
  { name: "Germany", capital: "Berlin", flag_url: "🇩🇪", continent: "Europe", region: "Western Europe" },
  { name: "Greece", capital: "Athens", flag_url: "🇬🇷", continent: "Europe", region: "Southern Europe" },
  { name: "Hungary", capital: "Budapest", flag_url: "🇭🇺", continent: "Europe", region: "Eastern Europe" },
  { name: "Iceland", capital: "Reykjavik", flag_url: "🇮🇸", continent: "Europe", region: "Northern Europe" },
  { name: "Ireland", capital: "Dublin", flag_url: "🇮🇪", continent: "Europe", region: "Western Europe" },
  { name: "Italy", capital: "Rome", flag_url: "🇮🇹", continent: "Europe", region: "Southern Europe" },
  { name: "Kosovo", capital: "Pristina", flag_url: "🇽🇰", continent: "Europe", region: "Southern Europe" },
  { name: "Latvia", capital: "Riga", flag_url: "🇱🇻", continent: "Europe", region: "Northern Europe" },
  { name: "Liechtenstein", capital: "Vaduz", flag_url: "🇱🇮", continent: "Europe", region: "Western Europe" },
  { name: "Lithuania", capital: "Vilnius", flag_url: "🇱🇹", continent: "Europe", region: "Northern Europe" },
  { name: "Luxembourg", capital: "Luxembourg City", flag_url: "🇱🇺", continent: "Europe", region: "Western Europe" },
  { name: "Malta", capital: "Valletta", flag_url: "🇲🇹", continent: "Europe", region: "Southern Europe" },
  { name: "Moldova", capital: "Chișinău", flag_url: "🇲🇩", continent: "Europe", region: "Eastern Europe" },
  { name: "Monaco", capital: "Monaco", flag_url: "🇲🇨", continent: "Europe", region: "Western Europe" },
  { name: "Montenegro", capital: "Podgorica", flag_url: "🇲🇪", continent: "Europe", region: "Southern Europe" },
  { name: "Netherlands", capital: "Amsterdam", flag_url: "🇳🇱", continent: "Europe", region: "Western Europe" },
  { name: "North Macedonia", capital: "Skopje", flag_url: "🇲🇰", continent: "Europe", region: "Southern Europe" },
  { name: "Norway", capital: "Oslo", flag_url: "🇳🇴", continent: "Europe", region: "Northern Europe" },
  { name: "Poland", capital: "Warsaw", flag_url: "🇵🇱", continent: "Europe", region: "Eastern Europe" },
  { name: "Portugal", capital: "Lisbon", flag_url: "🇵🇹", continent: "Europe", region: "Southern Europe" },
  { name: "Romania", capital: "Bucharest", flag_url: "🇷🇴", continent: "Europe", region: "Eastern Europe" },
  { name: "Russia", capital: "Moscow", flag_url: "🇷🇺", continent: "Europe", region: "Eastern Europe" },
  { name: "San Marino", capital: "San Marino", flag_url: "🇸🇲", continent: "Europe", region: "Southern Europe" },
  { name: "Serbia", capital: "Belgrade", flag_url: "🇷🇸", continent: "Europe", region: "Southern Europe" },
  { name: "Slovakia", capital: "Bratislava", flag_url: "🇸🇰", continent: "Europe", region: "Eastern Europe" },
  { name: "Slovenia", capital: "Ljubljana", flag_url: "🇸🇮", continent: "Europe", region: "Southern Europe" },
  { name: "Spain", capital: "Madrid", flag_url: "🇪🇸", continent: "Europe", region: "Southern Europe" },
  { name: "Sweden", capital: "Stockholm", flag_url: "🇸🇪", continent: "Europe", region: "Northern Europe" },
  { name: "Switzerland", capital: "Bern", flag_url: "🇨🇭", continent: "Europe", region: "Western Europe" },
  { name: "Ukraine", capital: "Kyiv", flag_url: "🇺🇦", continent: "Europe", region: "Eastern Europe" },
  { name: "United Kingdom", capital: "London", flag_url: "🇬🇧", continent: "Europe", region: "Western Europe" },
  { name: "Vatican City", capital: "Vatican City", flag_url: "🇻🇦", continent: "Europe", region: "Southern Europe" },

  // ── Asia (48 countries) ──
  { name: "Afghanistan", capital: "Kabul", flag_url: "🇦🇫", continent: "Asia", region: "South Asia" },
  { name: "Armenia", capital: "Yerevan", flag_url: "🇦🇲", continent: "Asia", region: "Western Asia" },
  { name: "Azerbaijan", capital: "Baku", flag_url: "🇦🇿", continent: "Asia", region: "Western Asia" },
  { name: "Bahrain", capital: "Manama", flag_url: "🇧🇭", continent: "Asia", region: "Western Asia" },
  { name: "Bangladesh", capital: "Dhaka", flag_url: "🇧🇩", continent: "Asia", region: "South Asia" },
  { name: "Bhutan", capital: "Thimphu", flag_url: "🇧🇹", continent: "Asia", region: "South Asia" },
  { name: "Brunei", capital: "Bandar Seri Begawan", flag_url: "🇧🇳", continent: "Asia", region: "Southeast Asia" },
  { name: "Cambodia", capital: "Phnom Penh", flag_url: "🇰🇭", continent: "Asia", region: "Southeast Asia" },
  { name: "China", capital: "Beijing", flag_url: "🇨🇳", continent: "Asia", region: "East Asia" },
  { name: "Georgia", capital: "Tbilisi", flag_url: "🇬🇪", continent: "Asia", region: "Western Asia" },
  { name: "India", capital: "New Delhi", flag_url: "🇮🇳", continent: "Asia", region: "South Asia" },
  { name: "Indonesia", capital: "Jakarta", flag_url: "🇮🇩", continent: "Asia", region: "Southeast Asia" },
  { name: "Iran", capital: "Tehran", flag_url: "🇮🇷", continent: "Asia", region: "Western Asia" },
  { name: "Iraq", capital: "Baghdad", flag_url: "🇮🇶", continent: "Asia", region: "Western Asia" },
  { name: "Israel", capital: "Jerusalem", flag_url: "🇮🇱", continent: "Asia", region: "Western Asia" },
  { name: "Japan", capital: "Tokyo", flag_url: "🇯🇵", continent: "Asia", region: "East Asia" },
  { name: "Jordan", capital: "Amman", flag_url: "🇯🇴", continent: "Asia", region: "Western Asia" },
  { name: "Kazakhstan", capital: "Astana", flag_url: "🇰🇿", continent: "Asia", region: "Central Asia" },
  { name: "Kuwait", capital: "Kuwait City", flag_url: "🇰🇼", continent: "Asia", region: "Western Asia" },
  { name: "Kyrgyzstan", capital: "Bishkek", flag_url: "🇰🇬", continent: "Asia", region: "Central Asia" },
  { name: "Laos", capital: "Vientiane", flag_url: "🇱🇦", continent: "Asia", region: "Southeast Asia" },
  { name: "Lebanon", capital: "Beirut", flag_url: "🇱🇧", continent: "Asia", region: "Western Asia" },
  { name: "Malaysia", capital: "Kuala Lumpur", flag_url: "🇲🇾", continent: "Asia", region: "Southeast Asia" },
  { name: "Maldives", capital: "Malé", flag_url: "🇲🇻", continent: "Asia", region: "South Asia" },
  { name: "Mongolia", capital: "Ulaanbaatar", flag_url: "🇲🇳", continent: "Asia", region: "East Asia" },
  { name: "Myanmar", capital: "Naypyidaw", flag_url: "🇲🇲", continent: "Asia", region: "Southeast Asia" },
  { name: "Nepal", capital: "Kathmandu", flag_url: "🇳🇵", continent: "Asia", region: "South Asia" },
  { name: "North Korea", capital: "Pyongyang", flag_url: "🇰🇵", continent: "Asia", region: "East Asia" },
  { name: "Oman", capital: "Muscat", flag_url: "🇴🇲", continent: "Asia", region: "Western Asia" },
  { name: "Pakistan", capital: "Islamabad", flag_url: "🇵🇰", continent: "Asia", region: "South Asia" },
  { name: "Palestine", capital: "Ramallah", flag_url: "🇵🇸", continent: "Asia", region: "Western Asia" },
  { name: "Philippines", capital: "Manila", flag_url: "🇵🇭", continent: "Asia", region: "Southeast Asia" },
  { name: "Qatar", capital: "Doha", flag_url: "🇶🇦", continent: "Asia", region: "Western Asia" },
  { name: "Saudi Arabia", capital: "Riyadh", flag_url: "🇸🇦", continent: "Asia", region: "Western Asia" },
  { name: "Singapore", capital: "Singapore", flag_url: "🇸🇬", continent: "Asia", region: "Southeast Asia" },
  { name: "South Korea", capital: "Seoul", flag_url: "🇰🇷", continent: "Asia", region: "East Asia" },
  { name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", flag_url: "🇱🇰", continent: "Asia", region: "South Asia" },
  { name: "Syria", capital: "Damascus", flag_url: "🇸🇾", continent: "Asia", region: "Western Asia" },
  { name: "Taiwan", capital: "Taipei", flag_url: "🇹🇼", continent: "Asia", region: "East Asia" },
  { name: "Tajikistan", capital: "Dushanbe", flag_url: "🇹🇯", continent: "Asia", region: "Central Asia" },
  { name: "Thailand", capital: "Bangkok", flag_url: "🇹🇭", continent: "Asia", region: "Southeast Asia" },
  { name: "Timor-Leste", capital: "Dili", flag_url: "🇹🇱", continent: "Asia", region: "Southeast Asia" },
  { name: "Turkey", capital: "Ankara", flag_url: "🇹🇷", continent: "Asia", region: "Western Asia" },
  { name: "Turkmenistan", capital: "Ashgabat", flag_url: "🇹🇲", continent: "Asia", region: "Central Asia" },
  { name: "United Arab Emirates", capital: "Abu Dhabi", flag_url: "🇦🇪", continent: "Asia", region: "Western Asia" },
  { name: "Uzbekistan", capital: "Tashkent", flag_url: "🇺🇿", continent: "Asia", region: "Central Asia" },
  { name: "Vietnam", capital: "Hanoi", flag_url: "🇻🇳", continent: "Asia", region: "Southeast Asia" },
  { name: "Yemen", capital: "Sana'a", flag_url: "🇾🇪", continent: "Asia", region: "Western Asia" },

  // ── North America (23 countries) ──
  { name: "Antigua and Barbuda", capital: "St. John's", flag_url: "🇦🇬", continent: "North America", region: "Caribbean" },
  { name: "Bahamas", capital: "Nassau", flag_url: "🇧🇸", continent: "North America", region: "Caribbean" },
  { name: "Barbados", capital: "Bridgetown", flag_url: "🇧🇧", continent: "North America", region: "Caribbean" },
  { name: "Belize", capital: "Belmopan", flag_url: "🇧🇿", continent: "North America", region: "Central America" },
  { name: "Canada", capital: "Ottawa", flag_url: "🇨🇦", continent: "North America", region: "Northern America" },
  { name: "Costa Rica", capital: "San José", flag_url: "🇨🇷", continent: "North America", region: "Central America" },
  { name: "Cuba", capital: "Havana", flag_url: "🇨🇺", continent: "North America", region: "Caribbean" },
  { name: "Dominica", capital: "Roseau", flag_url: "🇩🇲", continent: "North America", region: "Caribbean" },
  { name: "Dominican Republic", capital: "Santo Domingo", flag_url: "🇩🇴", continent: "North America", region: "Caribbean" },
  { name: "El Salvador", capital: "San Salvador", flag_url: "🇸🇻", continent: "North America", region: "Central America" },
  { name: "Grenada", capital: "St. George's", flag_url: "🇬🇩", continent: "North America", region: "Caribbean" },
  { name: "Guatemala", capital: "Guatemala City", flag_url: "🇬🇹", continent: "North America", region: "Central America" },
  { name: "Haiti", capital: "Port-au-Prince", flag_url: "🇭🇹", continent: "North America", region: "Caribbean" },
  { name: "Honduras", capital: "Tegucigalpa", flag_url: "🇭🇳", continent: "North America", region: "Central America" },
  { name: "Jamaica", capital: "Kingston", flag_url: "🇯🇲", continent: "North America", region: "Caribbean" },
  { name: "Mexico", capital: "Mexico City", flag_url: "🇲🇽", continent: "North America", region: "Northern America" },
  { name: "Nicaragua", capital: "Managua", flag_url: "🇳🇮", continent: "North America", region: "Central America" },
  { name: "Panama", capital: "Panama City", flag_url: "🇵🇦", continent: "North America", region: "Central America" },
  { name: "Saint Kitts and Nevis", capital: "Basseterre", flag_url: "🇰🇳", continent: "North America", region: "Caribbean" },
  { name: "Saint Lucia", capital: "Castries", flag_url: "🇱🇨", continent: "North America", region: "Caribbean" },
  { name: "Saint Vincent and the Grenadines", capital: "Kingstown", flag_url: "🇻🇨", continent: "North America", region: "Caribbean" },
  { name: "Trinidad and Tobago", capital: "Port of Spain", flag_url: "🇹🇹", continent: "North America", region: "Caribbean" },
  { name: "United States", capital: "Washington, D.C.", flag_url: "🇺🇸", continent: "North America", region: "Northern America" },

  // ── South America (12 countries) ──
  { name: "Argentina", capital: "Buenos Aires", flag_url: "🇦🇷", continent: "South America", region: null },
  { name: "Bolivia", capital: "Sucre", flag_url: "🇧🇴", continent: "South America", region: null },
  { name: "Brazil", capital: "Brasília", flag_url: "🇧🇷", continent: "South America", region: null },
  { name: "Chile", capital: "Santiago", flag_url: "🇨🇱", continent: "South America", region: null },
  { name: "Colombia", capital: "Bogotá", flag_url: "🇨🇴", continent: "South America", region: null },
  { name: "Ecuador", capital: "Quito", flag_url: "🇪🇨", continent: "South America", region: null },
  { name: "Guyana", capital: "Georgetown", flag_url: "🇬🇾", continent: "South America", region: null },
  { name: "Paraguay", capital: "Asunción", flag_url: "🇵🇾", continent: "South America", region: null },
  { name: "Peru", capital: "Lima", flag_url: "🇵🇪", continent: "South America", region: null },
  { name: "Suriname", capital: "Paramaribo", flag_url: "🇸🇷", continent: "South America", region: null },
  { name: "Uruguay", capital: "Montevideo", flag_url: "🇺🇾", continent: "South America", region: null },
  { name: "Venezuela", capital: "Caracas", flag_url: "🇻🇪", continent: "South America", region: null },

  // ── Oceania (14 countries) ──
  { name: "Australia", capital: "Canberra", flag_url: "🇦🇺", continent: "Oceania", region: "Australasia" },
  { name: "Fiji", capital: "Suva", flag_url: "🇫🇯", continent: "Oceania", region: "Melanesia" },
  { name: "Kiribati", capital: "Tarawa", flag_url: "🇰🇮", continent: "Oceania", region: "Micronesia" },
  { name: "Marshall Islands", capital: "Majuro", flag_url: "🇲🇭", continent: "Oceania", region: "Micronesia" },
  { name: "Micronesia", capital: "Palikir", flag_url: "🇫🇲", continent: "Oceania", region: "Micronesia" },
  { name: "Nauru", capital: "Yaren", flag_url: "🇳🇷", continent: "Oceania", region: "Micronesia" },
  { name: "New Zealand", capital: "Wellington", flag_url: "🇳🇿", continent: "Oceania", region: "Australasia" },
  { name: "Palau", capital: "Ngerulmud", flag_url: "🇵🇼", continent: "Oceania", region: "Micronesia" },
  { name: "Papua New Guinea", capital: "Port Moresby", flag_url: "🇵🇬", continent: "Oceania", region: "Melanesia" },
  { name: "Samoa", capital: "Apia", flag_url: "🇼🇸", continent: "Oceania", region: "Polynesia" },
  { name: "Solomon Islands", capital: "Honiara", flag_url: "🇸🇧", continent: "Oceania", region: "Melanesia" },
  { name: "Tonga", capital: "Nukuʻalofa", flag_url: "🇹🇴", continent: "Oceania", region: "Polynesia" },
  { name: "Tuvalu", capital: "Funafuti", flag_url: "🇹🇻", continent: "Oceania", region: "Polynesia" },
  { name: "Vanuatu", capital: "Port Vila", flag_url: "🇻🇺", continent: "Oceania", region: "Melanesia" },
];

export async function seed(knex: Knex): Promise<void> {
  await knex("countries").del();
  await knex("countries").insert(COUNTRIES);
}
